#pragma once
#include <stdint.h>
#include "../include/stereo_config.h"
#include "../include/stereo_types.h"

// ─── PL HLS: bilinear rectification ─────────────────────────────────────────
//
// Applies pre-computed undistort-rectify LUT (generated by OpenCV's
// initUndistortRectifyMap) to one image.  Both left and right images are
// processed through separate, parallel instances of this function.
//
// The remap LUT is stored in on-chip BRAM (dual-port, depth IMG_PIXELS,
// width 64 bits).  At 4K it occupies 3840×2160×8 B = 63 MB per image, so
// the LUT is partitioned across multiple BRAM banks and fetched via burst DMA
// into URAM at startup.  During streaming the LUT is accessed sequentially
// (raster-order output), allowing line-buffer prefetch to hide latency.
//
// Interfaces:
//   src      : AXI4-Master read  – raw sensor frame in DDR
//   lut      : AXI4-Master read  – remap LUT in DDR (cached in URAM)
//   dst      : AXI4-Master write – rectified frame in DDR
//   ctrl     : AXI4-Lite         – start/done/status

void rectify(
    const Pixel8*   src,          // [IMG_HEIGHT][IMG_WIDTH]  raw input
    const uint64_t* lut,          // [IMG_HEIGHT][IMG_WIDTH]  remap LUT
    Pixel8*         dst,          // [IMG_HEIGHT][IMG_WIDTH]  rectified output
    uint32_t        height,
    uint32_t        width);
